# Generated by Django 2.1.8 on 2020-04-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intworldapp', '0007_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_update_date',
        ),
    ]
