# Generated by Django 2.1.8 on 2020-04-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intworldapp', '0010_auto_20200415_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=140, unique=True)),
            ],
        ),
    ]
