# Generated by Django 2.1.8 on 2020-04-15 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intworldapp', '0011_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
