# Generated by Django 2.1.8 on 2020-04-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intworldapp', '0013_auto_20200415_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag_set',
            field=models.ManyToManyField(blank=True, null=True, to='intworldapp.Tag'),
        ),
    ]
