# Generated by Django 2.1.8 on 2020-04-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intworldapp', '0014_auto_20200415_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='post',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='intworldapp.Tag'),
        ),
    ]
