# Generated by Django 2.1.8 on 2020-04-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intworldapp', '0015_auto_20200415_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag_name',
        ),
    ]
